/**
 * Popular places configuration for each city
 * Curated list of must-visit locations
 */

export interface PopularPlace {
    id: string;
    name: string;
    nameRu: string;
    type: 'park' | 'mall' | 'monument' | 'museum' | 'attraction' | 'square' | 'building';
    description: string;
    descriptionRu: string;
    lat: number;
    lon: number;
    icon: string;
}

export const POPULAR_PLACES: Record<string, PopularPlace[]> = {
    tashkent: [
        {
            id: 'tashkent-city',
            name: 'Tashkent City',
            nameRu: 'Ташкент Сити',
            type: 'building',
            description: 'Modern business district with skyscrapers and shopping centers',
            descriptionRu: 'Современный деловой район с небоскрёбами и торговыми центрами',
            lat: 41.3111,
            lon: 69.2797,
            icon: '🏙️',
        },
        {
            id: 'amir-timur-square',
            name: 'Amir Timur Square',
            nameRu: 'Площадь Амира Темура',
            type: 'square',
            description: 'Central square with the monument to Amir Timur',
            descriptionRu: 'Центральная площадь с памятником Амиру Темуру',
            lat: 41.3111,
            lon: 69.2797,
            icon: '🗿',
        },
        {
            id: 'chorsu-bazaar',
            name: 'Chorsu Bazaar',
            nameRu: 'Чорсу Базар',
            type: 'attraction',
            description: 'Traditional oriental bazaar with local goods and food',
            descriptionRu: 'Традиционный восточный базар с местными товарами и едой',
            lat: 41.3263,
            lon: 69.2344,
            icon: '🏪',
        },
        {
            id: 'independence-square',
            name: 'Independence Square',
            nameRu: 'Площадь Независимости',
            type: 'square',
            description: 'Main square of Tashkent with beautiful fountains and parks',
            descriptionRu: 'Главная площадь Ташкента с красивыми фонтанами и парками',
            lat: 41.3117,
            lon: 69.2490,
            icon: '🌳',
        },
        {
            id: 'taras-shevchenko-park',
            name: 'Taras Shevchenko Park',
            nameRu: 'Парк Тараса Шевченко',
            type: 'park',
            description: 'Large park perfect for walking and relaxation',
            descriptionRu: 'Большой парк, идеален для прогулок и отдыха',
            lat: 41.3224,
            lon: 69.2496,
            icon: '🌲',
        },
        {
            id: 'magic-city',
            name: 'Magic City Park',
            nameRu: 'Парк Магик Сити',
            type: 'attraction',
            description: 'Amusement park with rides and entertainment',
            descriptionRu: 'Парк развлечений с аттракционами',
            lat: 41.2856,
            lon: 69.2034,
            icon: '🎡',
        },
    ],
    samarkand: [
        {
            id: 'registan',
            name: 'Registan Square',
            nameRu: 'Площадь Регистан',
            type: 'square',
            description: 'Iconic square with three madrasahs, UNESCO World Heritage Site',
            descriptionRu: 'Знаменитая площадь с тремя медресе, объект ЮНЕСКО',
            lat: 39.6547,
            lon: 66.9750,
            icon: '🕌',
        },
        {
            id: 'gur-emir',
            name: 'Gur-e-Amir Mausoleum',
            nameRu: 'Мавзолей Гур-Эмир',
            type: 'monument',
            description: 'Tomb of Amir Timur with stunning azure dome',
            descriptionRu: 'Гробница Амира Темура с потрясающим лазурным куполом',
            lat: 39.6481,
            lon: 66.9725,
            icon: '🕌',
        },
        {
            id: 'shah-i-zinda',
            name: 'Shah-i-Zinda',
            nameRu: 'Шахи Зинда',
            type: 'monument',
            description: 'Ancient necropolis with beautifully decorated mausoleums',
            descriptionRu: 'Древний некрополь с красиво украшенными мавзолеями',
            lat: 39.6625,
            lon: 66.9871,
            icon: '🏛️',
        },
        {
            id: 'bibi-khanum',
            name: 'Bibi-Khanym Mosque',
            nameRu: 'Мечеть Биби-Ханум',
            type: 'monument',
            description: 'Grand mosque built by Timur in the 15th century',
            descriptionRu: 'Величественная мечеть, построенная Тимуром в XV веке',
            lat: 39.6578,
            lon: 66.9786,
            icon: '🕌',
        },
        {
            id: 'siab-bazaar',
            name: 'Siab Bazaar',
            nameRu: 'Сиабский базар',
            type: 'attraction',
            description: 'Vibrant market near Bibi-Khanym Mosque',
            descriptionRu: 'Оживлённый рынок рядом с мечетью Биби-Ханум',
            lat: 39.6585,
            lon: 66.9795,
            icon: '🏪',
        },
        {
            id: 'ulugbek-observatory',
            name: "Ulugh Beg's Observatory",
            nameRu: 'Обсерватория Улугбека',
            type: 'museum',
            description: '15th-century astronomical observatory ruins',
            descriptionRu: 'Руины астрономической обсерватории XV века',
            lat: 39.6731,
            lon: 66.9872,
            icon: '🔭',
        },
    ],
    bukhara: [
        {
            id: 'ark-fortress',
            name: 'Ark Fortress',
            nameRu: 'Крепость Арк',
            type: 'monument',
            description: 'Ancient fortress and former residence of Bukhara khans',
            descriptionRu: 'Древняя крепость и бывшая резиденция бухарских ханов',
            lat: 39.7753,
            lon: 64.4144,
            icon: '🏰',
        },
        {
            id: 'poi-kalyan',
            name: 'Poi-Kalyan Complex',
            nameRu: 'Комплекс Пои-Калон',
            type: 'monument',
            description: 'Religious complex with famous Kalyan Minaret',
            descriptionRu: 'Религиозный комплекс со знаменитым минаретом Калян',
            lat: 39.7753,
            lon: 64.4197,
            icon: '🕌',
        },
        {
            id: 'lyabi-hauz',
            name: 'Lyab-i Hauz',
            nameRu: 'Ляби-Хауз',
            type: 'square',
            description: 'Central plaza around a historic pool',
            descriptionRu: 'Центральная площадь вокруг исторического водоёма',
            lat: 39.7747,
            lon: 64.4214,
            icon: '⛲',
        },
        {
            id: 'trading-domes',
            name: 'Trading Domes',
            nameRu: 'Торговые купола',
            type: 'attraction',
            description: 'Historic covered markets selling crafts and souvenirs',
            descriptionRu: 'Исторические крытые рынки с ремеслами и сувенирами',
            lat: 39.7750,
            lon: 64.4178,
            icon: '🏪',
        },
        {
            id: 'chor-minor',
            name: 'Chor Minor',
            nameRu: 'Чор-Минор',
            type: 'monument',
            description: 'Unique madrasah with four minarets',
            descriptionRu: 'Уникальное медресе с четырьмя минаретами',
            lat: 39.7719,
            lon: 64.4247,
            icon: '🕌',
        },
        {
            id: 'samanid-mausoleum',
            name: 'Samanid Mausoleum',
            nameRu: 'Мавзолей Саманидов',
            type: 'monument',
            description: 'Ancient mausoleum from the 9th-10th century',
            descriptionRu: 'Древний мавзолей IX-X веков',
            lat: 39.7716,
            lon: 64.4086,
            icon: '🏛️',
        },
    ],
    andijan: [
        {
            id: 'babur-square',
            name: 'Babur Square',
            nameRu: 'Площадь Бабура',
            type: 'square',
            description: 'Central square dedicated to the founder of Mughal Empire',
            descriptionRu: 'Центральная площадь, посвящённая основателю империи Великих Моголов',
            lat: 40.7821,
            lon: 72.3442,
            icon: '🗿',
        },
        {
            id: 'jami-mosque',
            name: 'Jami Mosque',
            nameRu: 'Мечеть Джами',
            type: 'monument',
            description: 'Beautiful 19th-century mosque in the city center',
            descriptionRu: 'Красивая мечеть XIX века в центре города',
            lat: 40.7856,
            lon: 72.3478,
            icon: '🕌',
        },
        {
            id: 'navoi-park',
            name: 'Navoi Park',
            nameRu: 'Парк Навои',
            type: 'park',
            description: 'Large recreational park with walking paths',
            descriptionRu: 'Большой парк отдыха с пешеходными дорожками',
            lat: 40.7789,
            lon: 72.3389,
            icon: '🌳',
        },
        {
            id: 'andijan-museum',
            name: 'Regional History Museum',
            nameRu: 'Областной музей истории',
            type: 'museum',
            description: 'Museum showcasing the history and culture of Fergana Valley',
            descriptionRu: 'Музей, демонстрирующий историю и культуру Ферганской долины',
            lat: 40.7845,
            lon: 72.3512,
            icon: '🏛️',
        },
    ],
    namangan: [
        {
            id: 'independence-park-namangan',
            name: 'Independence Park',
            nameRu: 'Парк Независимости',
            type: 'park',
            description: 'Central park with monuments and fountains',
            descriptionRu: 'Центральный парк с памятниками и фонтанами',
            lat: 41.0011,
            lon: 71.6683,
            icon: '🌳',
        },
        {
            id: 'mulla-kyrgyz-mosque',
            name: 'Mulla Kyrgyz Mosque',
            nameRu: 'Мечеть Мулла Кыргыз',
            type: 'monument',
            description: 'Historic mosque dating back to the 18th century',
            descriptionRu: 'Историческая мечеть XVIII века',
            lat: 40.9989,
            lon: 71.6645,
            icon: '🕌',
        },
        {
            id: 'ota-valikhon-tor',
            name: 'Ota Valikhon Tor',
            nameRu: 'Ота Валихон Тор',
            type: 'monument',
            description: 'Ancient madrasah and cultural heritage site',
            descriptionRu: 'Древнее медресе и памятник культурного наследия',
            lat: 40.9978,
            lon: 71.6723,
            icon: '🏛️',
        },
        {
            id: 'namangan-bazaar',
            name: 'Central Bazaar',
            nameRu: 'Центральный базар',
            type: 'attraction',
            description: 'Traditional market with local produce and crafts',
            descriptionRu: 'Традиционный рынок с местными продуктами и ремёслами',
            lat: 41.0045,
            lon: 71.6712,
            icon: '🏪',
        },
    ],
    fergana: [
        {
            id: 'al-fergani-park',
            name: 'Al-Fergani Park',
            nameRu: 'Парк Аль-Фергани',
            type: 'park',
            description: 'Beautiful park named after the famous mathematician',
            descriptionRu: 'Красивый парк, названный в честь известного математика',
            lat: 40.3864,
            lon: 71.7864,
            icon: '🌲',
        },
        {
            id: 'fergana-museum',
            name: 'Regional Museum',
            nameRu: 'Областной краеведческий музей',
            type: 'museum',
            description: 'Museum with collections on local history and ethnography',
            descriptionRu: 'Музей с коллекциями по местной истории и этнографии',
            lat: 40.3845,
            lon: 71.7889,
            icon: '🏛️',
        },
        {
            id: 'fergana-palace',
            name: 'Khudoyar Khan Palace',
            nameRu: 'Дворец Худояр-хана',
            type: 'monument',
            description: 'Historic palace showcasing traditional architecture',
            descriptionRu: 'Исторический дворец с традиционной архитектурой',
            lat: 40.3912,
            lon: 71.7823,
            icon: '🏰',
        },
        {
            id: 'victory-park-fergana',
            name: 'Victory Park',
            nameRu: 'Парк Победы',
            type: 'park',
            description: 'Memorial park dedicated to WWII veterans',
            descriptionRu: 'Мемориальный парк, посвящённый ветеранам ВОВ',
            lat: 40.3823,
            lon: 71.7901,
            icon: '🌳',
        },
    ],
    kokand: [
        {
            id: 'kokand-palace',
            name: 'Khudoyar Khan Palace',
            nameRu: 'Дворец Худояр-хана',
            type: 'monument',
            description: 'Magnificent palace with stunning tile work, 19th century',
            descriptionRu: 'Великолепный дворец с изумительной плиткой, XIX век',
            lat: 40.5286,
            lon: 70.9425,
            icon: '🏰',
        },
        {
            id: 'jami-mosque-kokand',
            name: 'Jami Mosque',
            nameRu: 'Мечеть Джами',
            type: 'monument',
            description: 'Large Friday mosque from 1800s with beautiful courtyard',
            descriptionRu: 'Большая пятничная мечеть 1800-х годов с красивым двором',
            lat: 40.5298,
            lon: 70.9412,
            icon: '🕌',
        },
        {
            id: 'norbutabiy-madrasah',
            name: 'Norbutabiy Madrasah',
            nameRu: 'Медресе Норбутабий',
            type: 'monument',
            description: 'Historical educational institution from 18th century',
            descriptionRu: 'Историческое учебное заведение XVIII века',
            lat: 40.5312,
            lon: 70.9445,
            icon: '🏛️',
        },
        {
            id: 'kokand-museum',
            name: 'Local History Museum',
            nameRu: 'Краеведческий музей',
            type: 'museum',
            description: 'Museum in historic building with regional artifacts',
            descriptionRu: 'Музей в историческом здании с региональными артефактами',
            lat: 40.5289,
            lon: 70.9438,
            icon: '🏛️',
        },
    ],
    nukus: [
        {
            id: 'savitsky-museum',
            name: 'Savitsky Museum',
            nameRu: 'Музей Савицкого',
            type: 'museum',
            description: 'World-renowned museum with avant-garde art collection',
            descriptionRu: 'Всемирно известный музей с коллекцией авангардного искусства',
            lat: 42.4531,
            lon: 59.6103,
            icon: '🎨',
        },
        {
            id: 'nukus-park',
            name: 'Central Park',
            nameRu: 'Центральный парк',
            type: 'park',
            description: 'Main recreational area in the city center',
            descriptionRu: 'Главная зона отдыха в центре города',
            lat: 42.4567,
            lon: 59.6089,
            icon: '🌳',
        },
        {
            id: 'karakalpakstan-museum',
            name: 'State Museum of Karakalpakstan',
            nameRu: 'Государственный музей Каракалпакстана',
            type: 'museum',
            description: 'Museum showcasing the history and culture of Karakalpakstan',
            descriptionRu: 'Музей, представляющий историю и культуру Каракалпакстана',
            lat: 42.4589,
            lon: 59.6134,
            icon: '🏛️',
        },
    ],
    urgench: [
        {
            id: 'urgench-monument',
            name: 'Al-Khorezmi Monument',
            nameRu: 'Памятник Аль-Хорезми',
            type: 'monument',
            description: 'Monument to the famous mathematician and astronomer',
            descriptionRu: 'Памятник знаменитому математику и астроному',
            lat: 41.5344,
            lon: 60.6247,
            icon: '🗿',
        },
        {
            id: 'urgench-park',
            name: 'City Park',
            nameRu: 'Городской парк',
            type: 'park',
            description: 'Green space for relaxation and recreation',
            descriptionRu: 'Зелёная зона для отдыха и развлечений',
            lat: 41.5389,
            lon: 60.6212,
            icon: '🌳',
        },
        {
            id: 'urgench-bazaar',
            name: 'Central Market',
            nameRu: 'Центральный рынок',
            type: 'attraction',
            description: 'Traditional market with local goods and produce',
            descriptionRu: 'Традиционный рынок с местными товарами и продуктами',
            lat: 41.5312,
            lon: 60.6289,
            icon: '🏪',
        },
    ],
    khiva: [
        {
            id: 'ichan-kala',
            name: 'Ichan Kala',
            nameRu: 'Ичан-Кала',
            type: 'monument',
            description: 'UNESCO World Heritage walled inner city, ancient fortress',
            descriptionRu: 'Объект ЮНЕСКО, обнесённый стеной внутренний город, древняя крепость',
            lat: 41.3814,
            lon: 60.3611,
            icon: '🏰',
        },
        {
            id: 'kalta-minor',
            name: 'Kalta Minor Minaret',
            nameRu: 'Минарет Кальта-Минор',
            type: 'monument',
            description: 'Iconic unfinished minaret with stunning turquoise tiles',
            descriptionRu: 'Знаменитый незавершённый минарет с бирюзовой плиткой',
            lat: 41.3789,
            lon: 60.3623,
            icon: '🕌',
        },
        {
            id: 'muhammad-amin-khan',
            name: 'Muhammad Amin Khan Madrasah',
            nameRu: 'Медресе Мухаммад Амин-хана',
            type: 'monument',
            description: 'Largest madrasah in Khiva, now converted to hotel',
            descriptionRu: 'Крупнейшее медресе в Хиве, теперь переделано в отель',
            lat: 41.3795,
            lon: 60.3617,
            icon: '🏛️',
        },
        {
            id: 'juma-mosque-khiva',
            name: 'Juma Mosque',
            nameRu: 'Мечеть Джума',
            type: 'monument',
            description: 'Ancient mosque with 218 wooden columns, 10th century',
            descriptionRu: 'Древняя мечеть с 218 деревянными колоннами, X век',
            lat: 41.3801,
            lon: 60.3589,
            icon: '🕌',
        },
        {
            id: 'tash-hauli',
            name: 'Tash Hauli Palace',
            nameRu: 'Дворец Таш-Хаули',
            type: 'monument',
            description: 'Beautiful palace with intricate tilework and courtyards',
            descriptionRu: 'Красивый дворец с замысловатой плиткой и дворами',
            lat: 41.3778,
            lon: 60.3645,
            icon: '🏰',
        },
    ],
    termez: [
        {
            id: 'kirk-kiz',
            name: 'Kirk Kiz Fortress',
            nameRu: 'Крепость Кирк-Киз',
            type: 'monument',
            description: 'Ancient fortress ruins from 9th century',
            descriptionRu: 'Руины древней крепости IX века',
            lat: 37.2170,
            lon: 67.2830,
            icon: '🏰',
        },
        {
            id: 'fayaz-tepe',
            name: 'Fayaz Tepe',
            nameRu: 'Фаяз-тепе',
            type: 'monument',
            description: 'Ancient Buddhist monastery complex',
            descriptionRu: 'Древний буддийский монастырский комплекс',
            lat: 37.2234,
            lon: 67.2956,
            icon: '🏛️',
        },
        {
            id: 'termez-museum',
            name: 'Archaeological Museum',
            nameRu: 'Археологический музей',
            type: 'museum',
            description: 'Museum with Buddhist and Islamic artifacts',
            descriptionRu: 'Музей с буддийскими и исламскими артефактами',
            lat: 37.2189,
            lon: 67.2867,
            icon: '🏛️',
        },
        {
            id: 'sultan-saodat',
            name: 'Sultan Saodat Complex',
            nameRu: 'Комплекс Султан Саодат',
            type: 'monument',
            description: 'Architectural ensemble with mausoleums from 11th-17th centuries',
            descriptionRu: 'Архитектурный ансамбль с мавзолеями XI-XVII веков',
            lat: 37.2145,
            lon: 67.2789,
            icon: '🕌',
        },
    ],
    qarshi: [
        {
            id: 'qarshi-mosque',
            name: 'Kok Gumbaz Mosque',
            nameRu: 'Мечеть Кок-Гумбаз',
            type: 'monument',
            description: 'Historic blue-domed mosque from 16th century',
            descriptionRu: 'Историческая мечеть с голубым куполом XVI века',
            lat: 38.8670,
            lon: 65.8000,
            icon: '🕌',
        },
        {
            id: 'qarshi-bazaar',
            name: 'Central Bazaar',
            nameRu: 'Центральный базар',
            type: 'attraction',
            description: 'Vibrant market in the heart of the city',
            descriptionRu: 'Оживлённый рынок в самом центре города',
            lat: 38.8689,
            lon: 65.8023,
            icon: '🏪',
        },
        {
            id: 'qarshi-park',
            name: 'Independence Park',
            nameRu: 'Парк Независимости',
            type: 'park',
            description: 'Central park with monuments and green spaces',
            descriptionRu: 'Центральный парк с памятниками и зелёными зонами',
            lat: 38.8645,
            lon: 65.7978,
            icon: '🌳',
        },
    ],
    navoi: [
        {
            id: 'navoi-monument',
            name: 'Alisher Navoi Monument',
            nameRu: 'Памятник Алишеру Навои',
            type: 'monument',
            description: 'Monument to the great Uzbek poet and statesman',
            descriptionRu: 'Памятник великому узбекскому поэту и государственному деятелю',
            lat: 40.0844,
            lon: 65.3792,
            icon: '🗿',
        },
        {
            id: 'navoi-park-center',
            name: 'Central Park',
            nameRu: 'Центральный парк',
            type: 'park',
            description: 'Modern park with walking paths and recreation areas',
            descriptionRu: 'Современный парк с пешеходными дорожками и зонами отдыха',
            lat: 40.0878,
            lon: 65.3756,
            icon: '🌳',
        },
        {
            id: 'navoi-museum',
            name: 'History Museum',
            nameRu: 'Музей истории',
            type: 'museum',
            description: 'Museum showcasing the mining and industrial heritage',
            descriptionRu: 'Музей, демонстрирующий горнодобывающее и промышленное наследие',
            lat: 40.0823,
            lon: 65.3812,
            icon: '🏛️',
        },
    ],
    zarafshan: [
        {
            id: 'zarafshan-park',
            name: 'City Park',
            nameRu: 'Городской парк',
            type: 'park',
            description: 'Green oasis in the mining city',
            descriptionRu: 'Зелёный оазис в горнодобывающем городе',
            lat: 41.5744,
            lon: 64.1833,
            icon: '🌳',
        },
        {
            id: 'zarafshan-square',
            name: 'Central Square',
            nameRu: 'Центральная площадь',
            type: 'square',
            description: 'Main city square with cultural events',
            descriptionRu: 'Главная городская площадь с культурными мероприятиями',
            lat: 41.5767,
            lon: 64.1856,
            icon: '⛲',
        },
    ],
    jizzakh: [
        {
            id: 'jizzakh-park',
            name: 'Friendship Park',
            nameRu: 'Парк Дружбы',
            type: 'park',
            description: 'Popular park for families and recreation',
            descriptionRu: 'Популярный парк для семейного отдыха',
            lat: 40.1158,
            lon: 67.8422,
            icon: '🌳',
        },
        {
            id: 'jizzakh-museum',
            name: 'Regional Museum',
            nameRu: 'Областной музей',
            type: 'museum',
            description: 'Museum with local history and ethnographic exhibits',
            descriptionRu: 'Музей с экспозициями по местной истории и этнографии',
            lat: 40.1189,
            lon: 67.8445,
            icon: '🏛️',
        },
        {
            id: 'jizzakh-square',
            name: 'Independence Square',
            nameRu: 'Площадь Независимости',
            type: 'square',
            description: 'Central square with monuments and fountains',
            descriptionRu: 'Центральная площадь с памятниками и фонтанами',
            lat: 40.1134,
            lon: 67.8401,
            icon: '⛲',
        },
    ],
    guliston: [
        {
            id: 'guliston-park',
            name: 'Central Park',
            nameRu: 'Центральный парк',
            type: 'park',
            description: 'Main park for recreation and leisure',
            descriptionRu: 'Главный парк для отдыха и развлечений',
            lat: 40.4897,
            lon: 68.7842,
            icon: '🌳',
        },
        {
            id: 'guliston-square',
            name: 'City Square',
            nameRu: 'Городская площадь',
            type: 'square',
            description: 'Central gathering place with cultural activities',
            descriptionRu: 'Центральное место встреч с культурными мероприятиями',
            lat: 40.4923,
            lon: 68.7867,
            icon: '⛲',
        },
    ],
    angren: [
        {
            id: 'angren-park',
            name: 'City Park',
            nameRu: 'Городской парк',
            type: 'park',
            description: 'Green space in the industrial city',
            descriptionRu: 'Зелёная зона в промышленном городе',
            lat: 41.0084,
            lon: 70.0741,
            icon: '🌳',
        },
        {
            id: 'angren-monument',
            name: 'Miners Monument',
            nameRu: 'Памятник шахтёрам',
            type: 'monument',
            description: 'Memorial dedicated to coal miners',
            descriptionRu: 'Мемориал, посвящённый угольщикам',
            lat: 41.0112,
            lon: 70.0789,
            icon: '🗿',
        },
    ],
    chirchiq: [
        {
            id: 'chirchiq-park',
            name: 'Victory Park',
            nameRu: 'Парк Победы',
            type: 'park',
            description: 'Memorial park with WWII monuments',
            descriptionRu: 'Мемориальный парк с памятниками ВОВ',
            lat: 41.4689,
            lon: 69.5822,
            icon: '🌳',
        },
        {
            id: 'chirchiq-square',
            name: 'Central Square',
            nameRu: 'Центральная площадь',
            type: 'square',
            description: 'Main square with fountains and monuments',
            descriptionRu: 'Главная площадь с фонтанами и памятниками',
            lat: 41.4712,
            lon: 69.5845,
            icon: '⛲',
        },
    ],
    almalyk: [
        {
            id: 'almalyk-park',
            name: 'Metallurgists Park',
            nameRu: 'Парк Металлургов',
            type: 'park',
            description: 'Park dedicated to the citys industrial workers',
            descriptionRu: 'Парк, посвящённый промышленным рабочим города',
            lat: 40.8447,
            lon: 69.5983,
            icon: '🌳',
        },
        {
            id: 'almalyk-monument',
            name: 'Workers Monument',
            nameRu: 'Памятник труженикам',
            type: 'monument',
            description: 'Monument honoring the citys metallurgical workers',
            descriptionRu: 'Памятник, чтящий металлургов города',
            lat: 40.8478,
            lon: 69.6012,
            icon: '🗿',
        },
    ],
};
